# Generated by Django 4.2.8 on 2024-02-04 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0407_alter_dailyround_additional_symptoms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientconsultation",
            name="last_consultation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="facility.patientconsultation",
            ),
        ),
    ]
